import { exec } from 'child_process';
import { promisify } from 'util';
import { SpecFile } from '../../core/SpecParser';
import chalk from 'chalk';

const execAsync = promisify(exec);

export interface GitConfig {
  auto_pr: boolean;
  pr_base_branch?: string;
  pr_template?: string;
}

export interface PROptions {
  spec: SpecFile;
  branch: string;
  filesChanged: number;
  buildStatus: string;
}

export interface PRResult {
  url: string;
  number: number;
}

/**
 * PRManager - Handles automatic PR creation via gh CLI
 *
 * NEW in v1.2: Supports auto PR creation for CI/CD workflows
 */
export class PRManager {
  constructor(
    private repoPath: string,
    private config: GitConfig
  ) {}

  /**
   * Create a pull request if auto_pr is enabled
   */
  async createPR(options: PROptions): Promise<PRResult | null> {
    if (!this.config.auto_pr) {
      return null; // User will create PR manually
    }

    // Check if gh CLI is installed
    try {
      await execAsync('gh --version', { cwd: this.repoPath });
    } catch (error) {
      console.log(chalk.yellow('⚠️  gh CLI not installed. Install from: https://cli.github.com/'));
      console.log(chalk.yellow('   Skipping auto PR creation.'));
      return null;
    }

    // Render PR title and body
    const title = `[MyIntern] ${options.spec.title}`;
    const body = this.renderTemplate(
      this.config.pr_template || this.getDefaultTemplate(),
      {
        spec_name: options.spec.filePath.split('/').pop() || 'unknown',
        files_changed: options.filesChanged,
        build_status: options.buildStatus,
        spec_title: options.spec.title,
        spec_type: options.spec.type
      }
    );

    // Create PR
    const baseBranch = this.config.pr_base_branch || 'main';
    console.log(chalk.blue(`\n   📤 Creating PR against ${baseBranch}...`));

    try {
      const { stdout } = await execAsync(
        `gh pr create --base "${baseBranch}" --title "${title}" --body "${body}"`,
        { cwd: this.repoPath }
      );

      // Parse PR URL from output
      const url = stdout.match(/https:\/\/github\.com\/[^\s]+/)?.[0] || '';
      const number = parseInt(url.split('/').pop() || '0', 10);

      console.log(chalk.green(`   ✓ PR created: ${url}`));

      return { url, number };
    } catch (error: any) {
      console.log(chalk.red(`   ✗ Failed to create PR: ${error.message}`));
      return null;
    }
  }

  /**
   * Render template with variables
   */
  private renderTemplate(template: string, vars: Record<string, any>): string {
    let rendered = template;
    for (const [key, value] of Object.entries(vars)) {
      rendered = rendered.replace(new RegExp(`{{${key}}}`, 'g'), String(value));
    }
    return rendered;
  }

  /**
   * Get default PR template
   */
  private getDefaultTemplate(): string {
    return `## Summary
Generated by MyIntern for spec: {{spec_name}}

**Type:** {{spec_type}}

## Changes
- {{files_changed}} files modified

## Build Status
{{build_status}}

---
🤖 Generated with [MyIntern](https://github.com/myinterndev/myintern)
`;
  }
}
