import chalk from 'chalk';
import type { GitHubMCPClient, GitHubMCPConfig, GitHubPullRequest } from '../mcp/GitHubMCPClient';

export interface PRLifecycleResult {
  status: 'success' | 'ci_failed' | 'skipped';
  pr?: GitHubPullRequest;
  failureReason?: string;
}

export interface PRLifecycleOptions {
  specName: string;
  specTitle: string;
  branch: string;
  filesChanged: number;
}

export class GitHubLifecycle {
  constructor(
    private readonly client: GitHubMCPClient,
    private readonly config: GitHubMCPConfig
  ) {}

  /**
   * Full PR lifecycle: create → optionally wait for checks → optionally auto-merge.
   */
  async createAndMonitorPR(options: PRLifecycleOptions): Promise<PRLifecycleResult> {
    if (!this.config.pr || this.config.pr.auto_create === false) {
      return { status: 'skipped' };
    }

    const baseBranch = this.config.pr.base_branch || 'main';
    const draft = this.config.pr.draft !== false; // default: true

    const bodyTemplate = this.config.pr.template || this.getDefaultTemplate();
    const body = this.renderTemplate(bodyTemplate, {
      spec_name: options.specName,
      spec_title: options.specTitle,
      files_changed: options.filesChanged,
      build_status: 'passed'
    });

    await this.client.connect();

    // Create PR
    const pr = await this.client.createPullRequest({
      title: `[MyIntern] ${options.specTitle}`,
      body,
      head: options.branch,
      base: baseBranch,
      draft,
      reviewers: this.config.pr.reviewers || [],
      labels: this.config.pr.labels || ['myintern-generated']
    });

    console.log(chalk.green(`   ✓ PR created via GitHub MCP: ${pr.url}`));

    // Wait for checks if configured
    if (this.config.actions?.wait_for_checks) {
      const timeoutMs = this.config.actions.check_timeout_ms ?? 300000;
      const checks = await this.client.waitForChecks(pr.number, timeoutMs);

      if (!checks.passed) {
        return {
          status: 'ci_failed',
          pr,
          failureReason: 'One or more checks failed'
        };
      }
    }

    // Auto-merge if enabled and CI passed
    if (this.config.pr.auto_merge) {
      await this.client.mergePullRequest(pr.number, {
        merge_method: 'squash'
      });
      console.log(chalk.green(`   ✓ PR auto-merged via GitHub MCP: #${pr.number}`));
    }

    return { status: 'success', pr };
  }

  private renderTemplate(template: string, vars: Record<string, any>): string {
    let rendered = template;
    for (const [key, value] of Object.entries(vars)) {
      rendered = rendered.replaceAll(new RegExp(`{{${key}}}`, 'g'), String(value));
    }
    return rendered;
  }

  private getDefaultTemplate(): string {
    return `## Summary
Generated by MyIntern for spec: {{spec_name}}

## Changes
- {{files_changed}} files modified

## Build Status
{{build_status}}
`;
  }
}

